define([], function() {
  return {
    Yes: 'Yes',
    No: 'No',
    Save: 'Save',
    Cancel: 'Cancel',
    Delete: 'Delete',
    ToggleOnAriaLabel: 'This toggle is checked. Press to uncheck.',
    ToggleOffAriaLabel: 'This toggle is unchecked. Press to check.',
    ToggleOnText: 'Yes',
    ToggleOffText: 'No',
    DateFormFieldPlaceholder: 'Enter a date',
    UrlFormFieldPlaceholder: 'Enter url link',
    UrlDescFormFieldPlaceholder: 'Enter url link name',
    TextFormFieldPlaceholder: 'Enter text',
    UserFormFieldPlaceholder: 'Select user',
    UsersFormFieldPlaceholder: 'Select one or more user(s)',
    ChoiceFormFieldPlaceholder: 'Select an option',
    MultiChoiceFormFieldPlaceholder: 'Select one or more option(s)',
    NumberFormFieldPlaceholder: 'Select a number',
    AddAttachment: 'Add new attachment',
    ItemSavedSuccessfully: 'Item saved successfully.',
    InvalidNumberValue: 'Invalid number',
    months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    shortMonths: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    days: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    shortDays: ['S', 'M', 'T', 'W', 'T', 'F', 'S'],
    goToToday: 'Go to today',
    prevMonthAriaLabel: 'Go to previous month',
    nextMonthAriaLabel: 'Go to next month',
    prevYearAriaLabel: 'Go to previous year',
    nextYearAriaLabel: 'Go to next year',
    Errors: {
      ErrorWebAccessDenied: 'Access denied!',
      ErrorOnLoadingApp: 'Error on loading app!',
      ErrorWebNotFound: 'Web not found!',
      RequiredValueMessage: 'This field is required!',
      ErrorOnSavingListItem: 'Error on saving item!',
      ErrorDuplicateAttachment: 'Duplicate file, file was renamed - Dupl_file name.',
      FieldsErrorOnSaving: 'The item could not be saved. Please check detailed error messages on the fields below.',
      ErrorNoFields: 'Error: No fields to show.'
    }
  }
});