define([], function() {
  return {
    Yes: 'Áno',
    No: 'Nie',
    Save: 'Uložiť',
    Cancel: 'Zrušiť',
    Delete: 'Vymazať',
    ToggleOnAriaLabel: 'Prepínač je zapnutý. Stlačte na vypnutie.',
    ToggleOffAriaLabel: 'Prepínač je vypnutý. Stlačte na zapnutie.',
    ToggleOnText: 'Áno',
    ToggleOffText: 'Nie',
    DateFormFieldPlaceholder: 'Zadajte dátum',
    UrlFormFieldPlaceholder: 'Zadajte url odkaz',
    UrlDescFormFieldPlaceholder: 'Zadajte meno odkazu',
    TextFormFieldPlaceholder: 'Zadajte text',
    UserFormFieldPlaceholder: 'Vyberte používateľa',
    UsersFormFieldPlaceholder: 'Vyberte jedného alebo viacerých používateľov',
    ChoiceFormFieldPlaceholder: 'Vyberte možnosť',
    MultiChoiceFormFieldPlaceholder: 'Vyberte jednu alebo viacero možností',
    NumberFormFieldPlaceholder: 'Zadjte číslo',
    AddAttachment: 'Pridať prílohu',
    ItemSavedSuccessfully: 'Záznam bol úspešne uložený.',
    InvalidNumberValue: 'Neplatné číslo',
    months: ['Január', 'Február', 'Marec', 'Apríl', 'Máj', 'Jún', 'Júl', 'August', 'September', 'Október', 'November', 'December'],
    shortMonths: ['Jan', 'Feb', 'Mar', 'Apr', 'Máj', 'Jún', 'Júl', 'Aug', 'Sep', 'Okt', 'Nov', 'Dec'],
    days: ['Nedeľa', 'Pondelok', 'Utorok', 'Streda', 'Štvrtok', 'Piatok', 'Sobota'],
    shortDays: ['Ne', 'Po', 'Ut', 'St', 'Št', 'Pi', 'So'],
    goToToday: 'Dnes',
    prevMonthAriaLabel: 'Predchádzajúci mesiac',
    nextMonthAriaLabel: 'Nasledujúci mesiac',
    prevYearAriaLabel: 'Prechádzajúci rok',
    nextYearAriaLabel: 'Nasledujúci rok',
    Errors: {
      ErrorWebAccessDenied: 'Nemáte prístup!',
      ErrorOnLoadingApp: 'Chyba pri úvodnom načítavaní aplikácie. Ak problém pretrváva, konktaktuje prosím podporu.',
      ErrorWebNotFound: 'Nakonfigurovaná adresa nie je dostupná.',
      RequiredValueMessage: 'Prosím zadajte hodnotu!',
      ErrorOnSavingListItem: 'Chyba pri ukladaní záznamu!',
      ErrorDuplicateAttachment: 'Duplicate file, file was renamed - Dupl_file name.',
      FieldsErrorOnSaving: 'Záznam sa nepodarilo uložiť. Prosím skontrolujte prípadné chyby pod atribútmi.',
      ErrorNoFields: 'Neexistujú atribúty záznamu na zobrazenie.'
    }
  }
});